---@meta

-- Grid Protocol — Element Type Annotations
-- LuaCATS annotations for Grid firmware element-method API
-- https://github.com/intechstudio/grid-protocol
--
-- Each element type (Button, Potmeter, Encoder, Endless, LCD, System) is
-- modelled as a @class.  In user code these are accessed as `self:method()`
-- inside event callbacks, or `element[i]:method()` from any context.
--
-- Hand-enriched entries give full @param / @return detail.
-- Entries generated by scaffold_annotations.py are marked [scaffold].

---------------------------------------------------------------------------
-- Shared fields
---------------------------------------------------------------------------

---@class ElementBase
---@field type string Element type identifier
local ElementBase = {}

---Returns the zero-based element index.
---@return integer index
function ElementBase:element_index() end

---Returns the hardware LED index for this element.
---@return integer led_index
function ElementBase:led_index() end

---Gets or sets the element display name.
---@param name? string Optional name to set
---@return string name
function ElementBase:element_name(name) end

---------------------------------------------------------------------------
-- ButtonElement
---------------------------------------------------------------------------

---@class ButtonElement : ElementBase
local ButtonElement = {}

---Gets or sets the button value.
---@param value? integer Value to set (0–127 by default)
---@return integer value Current button value
function ButtonElement:button_value(value) end

---Gets or sets the button minimum.
---@param value? integer Minimum to set
---@return integer min Current minimum
function ButtonElement:button_min(value) end

---Gets or sets the button maximum.
---@param value? integer Maximum to set
---@return integer max Current maximum
function ButtonElement:button_max(value) end

---Gets or sets the button mode (step count). 0 = momentary.
---@param value? integer Mode / step count
---@return integer mode Current mode
function ButtonElement:button_mode(value) end

---Returns the elapsed time since last button event in ms.
---@return integer ms
function ButtonElement:button_elapsed_time() end

---Returns the button state (0 = released, 127 = pressed).
---@return integer state
function ButtonElement:button_state() end

---Returns the current step index, or false if mode is 0.
---@return integer|false step
function ButtonElement:button_step() end

---Sets or gets the LED color for this element.
---@param layer integer LED layer index
---@param colors table Color specification
function ButtonElement:led_color(layer, colors) end

---------------------------------------------------------------------------
-- PotmeterElement
---------------------------------------------------------------------------

---@class PotmeterElement : ElementBase
local PotmeterElement = {}

---Gets or sets the potentiometer value.
---@param value? integer Value to set
---@return integer value Current value
function PotmeterElement:potmeter_value(value) end

---Gets or sets the potentiometer minimum.
---@param value? integer
---@return integer min
function PotmeterElement:potmeter_min(value) end

---Gets or sets the potentiometer maximum.
---@param value? integer
---@return integer max
function PotmeterElement:potmeter_max(value) end

---Gets or sets the potentiometer resolution / mode.
---@param value? integer Bit depth (e.g. 7 = 128 steps)
---@return integer resolution
function PotmeterElement:potmeter_resolution(value) end

---Returns elapsed time since last potentiometer event in ms.
---@return integer ms
function PotmeterElement:potmeter_elapsed_time() end

---Returns the potentiometer state.
---@return integer state
function PotmeterElement:potmeter_state() end

---------------------------------------------------------------------------
-- EncoderElement
---------------------------------------------------------------------------

---@class EncoderElement : ElementBase
local EncoderElement = {}

-- Encoder inherits button methods (the encoder push-button)

---Gets or sets the button value.
---@param value? integer
---@return integer value
function EncoderElement:button_value(value) end

---Gets or sets the button minimum.
---@param value? integer
---@return integer min
function EncoderElement:button_min(value) end

---Gets or sets the button maximum.
---@param value? integer
---@return integer max
function EncoderElement:button_max(value) end

---Gets or sets the button mode.
---@param value? integer
---@return integer mode
function EncoderElement:button_mode(value) end

---@return integer ms
function EncoderElement:button_elapsed_time() end

---@return integer state
function EncoderElement:button_state() end

---@return integer|false step
function EncoderElement:button_step() end

-- Encoder-specific methods

---Returns the encoder rotation number / counter.
---@return integer number
function EncoderElement:encoder_number() end

---Gets or sets the encoder value.
---@param value? integer
---@return integer value
function EncoderElement:encoder_value(value) end

---Gets or sets the encoder minimum.
---@param value? integer
---@return integer min
function EncoderElement:encoder_min(value) end

---Gets or sets the encoder maximum.
---@param value? integer
---@return integer max
function EncoderElement:encoder_max(value) end

---Gets or sets the encoder mode.
---@param value? integer
---@return integer mode
function EncoderElement:encoder_mode(value) end

---Returns elapsed time since last encoder event in ms.
---@return integer ms
function EncoderElement:encoder_elapsed_time() end

---Returns the encoder state.
---@return integer state
function EncoderElement:encoder_state() end

---Returns the encoder velocity.
---@return integer velocity
function EncoderElement:encoder_velocity() end

---Gets or sets the encoder sensitivity.
---@param value? integer
---@return integer sensitivity
function EncoderElement:encoder_sensitivity(value) end

---Sets or gets the LED color for this element.
---@param layer integer LED layer index
---@param colors table Color specification
function EncoderElement:led_color(layer, colors) end

---------------------------------------------------------------------------
-- EndlessElement
---------------------------------------------------------------------------

---@class EndlessElement : ElementBase
local EndlessElement = {}

-- Endless inherits button methods

---Gets or sets the button value.
---@param value? integer
---@return integer value
function EndlessElement:button_value(value) end

---Gets or sets the button minimum.
---@param value? integer
---@return integer min
function EndlessElement:button_min(value) end

---Gets or sets the button maximum.
---@param value? integer
---@return integer max
function EndlessElement:button_max(value) end

---Gets or sets the button mode.
---@param value? integer
---@return integer mode
function EndlessElement:button_mode(value) end

---@return integer ms
function EndlessElement:button_elapsed_time() end

---@return integer state
function EndlessElement:button_state() end

-- Endless-specific methods

---Returns the LED offset for the endless ring.
---@return integer offset
function EndlessElement:led_offset() end

---Gets or sets the endless potentiometer value.
---@param value? integer
---@return integer value
function EndlessElement:endless_value(value) end

---Gets or sets the endless minimum.
---@param value? integer
---@return integer min
function EndlessElement:endless_min(value) end

---Gets or sets the endless maximum.
---@param value? integer
---@return integer max
function EndlessElement:endless_max(value) end

---Gets or sets the endless mode.
---@param value? integer
---@return integer mode
function EndlessElement:endless_mode(value) end

---Returns elapsed time since last endless event in ms.
---@return integer ms
function EndlessElement:endless_elapsed_time() end

---Returns the endless state.
---@return integer state
function EndlessElement:endless_state() end

---Returns the endless velocity.
---@return integer velocity
function EndlessElement:endless_velocity() end

---Returns the endless rotation direction (-1 or 1).
---@return integer direction
function EndlessElement:endless_direction() end

---Gets or sets the endless sensitivity.
---@param value? integer
---@return integer sensitivity
function EndlessElement:endless_sensitivity(value) end

---------------------------------------------------------------------------
-- LcdElement
---------------------------------------------------------------------------

---@class LcdElement : ElementBase
local LcdElement = {}

---Returns the screen index used by low-level draw APIs.
---@return integer screen_index
function LcdElement:screen_index() end

---Returns the screen width in pixels.
---@return integer width
function LcdElement:screen_width() end

---Returns the screen height in pixels.
---@return integer height
function LcdElement:screen_height() end

---Swaps the background buffer to the screen.
function LcdElement:draw_swap() end

---Draws a pixel at (x, y).
---@param x integer
---@param y integer
---@param color integer[] {r, g, b}
function LcdElement:draw_pixel(x, y, color) end

---Draws a line.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function LcdElement:draw_line(x1, y1, x2, y2, color) end

---Draws a rectangle outline.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function LcdElement:draw_rectangle(x1, y1, x2, y2, color) end

---Draws a filled rectangle.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function LcdElement:draw_rectangle_filled(x1, y1, x2, y2, color) end

---Draws a rounded rectangle outline.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param radius integer Corner radius in pixels
---@param color integer[] {r, g, b}
function LcdElement:draw_rectangle_rounded(x1, y1, x2, y2, radius, color) end

---Draws a filled rounded rectangle.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param radius integer Corner radius in pixels
---@param color integer[] {r, g, b}
function LcdElement:draw_rectangle_rounded_filled(x1, y1, x2, y2, radius, color) end

---Draws a polygon outline.
---@param xs integer[] X coordinates
---@param ys integer[] Y coordinates
---@param color integer[] {r, g, b}
function LcdElement:draw_polygon(xs, ys, color) end

---Draws a filled polygon.
---@param xs integer[] X coordinates
---@param ys integer[] Y coordinates
---@param color integer[] {r, g, b}
function LcdElement:draw_polygon_filled(xs, ys, color) end

---Draws text.
---@param text string
---@param x integer
---@param y integer
---@param size integer Font size
---@param color integer[] {r, g, b}
function LcdElement:draw_text(text, x, y, size, color) end

---Draws text using the fast renderer.
---@param text string
---@param x integer
---@param y integer
---@param size integer Font size
---@param color integer[] {r, g, b}
function LcdElement:draw_text_fast(text, x, y, size, color) end

---Fills an area without alpha blending.
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function LcdElement:draw_area_filled(x1, y1, x2, y2, color) end

---Draws the n-th demo iteration.
---@param n integer
function LcdElement:draw_demo(n) end

---Returns render time between last two swaps, in µs.
---@return integer us
function LcdElement:get_render_time() end

---------------------------------------------------------------------------
-- SystemElement
---------------------------------------------------------------------------

---@class SystemElement : ElementBase
local SystemElement = {}

---------------------------------------------------------------------------
-- Element array
---------------------------------------------------------------------------

---The global element array; element[0] is typically the system element,
---element[1..N] are the physical controls.
---@type (ButtonElement|PotmeterElement|EncoderElement|EndlessElement|LcdElement|SystemElement)[]
element = {}

---Reference to the current element inside an event callback.
---@type ButtonElement|PotmeterElement|EncoderElement|EndlessElement|LcdElement|SystemElement
self = nil
