---@meta

-- Grid Protocol — Global Functions
-- LuaCATS annotations for the Grid firmware Lua API
-- https://github.com/intechstudio/grid-protocol
--
-- This file contains type stubs for GLOBAL functions (prefix "G" in
-- grid_protocol_bot.json).  Element-method stubs live in elements.lua.
--
-- Hand-enriched entries give full @param / @return / @overload detail.
-- Entries generated by scaffold_annotations.py are marked [scaffold].

---------------------------------------------------------------------------
-- MIDI
---------------------------------------------------------------------------

---Sends a standard MIDI message.
---@param channel integer MIDI channel (0–15)
---@param command integer MIDI status byte — e.g. 176 (CC), 144 (Note On)
---@param parameter1 integer First data byte (0–127)
---@param parameter2 integer Second data byte (0–127)
function midi_send(channel, command, parameter1, parameter2) end

---Sends a MIDI SysEx message.
---@param ... integer Variadic SysEx data bytes
function midi_sysex_send(...) end

---------------------------------------------------------------------------
-- Mapping / Math
---------------------------------------------------------------------------

---Linearly maps *value* from [from_min, from_max] to [to_min, to_max]
---and saturates the result to [to_min, to_max].
---@param value number Input value
---@param from_min number Source range minimum
---@param from_max number Source range maximum
---@param to_min number Target range minimum
---@param to_max number Target range maximum
---@return number mapped Mapped and clamped result
function map_saturate(value, from_min, from_max, to_min, to_max) end

---Calculates the intensity value for a single LED segment when
---visualising an endless-encoder position.
---@param value integer Current encoder value
---@param min integer Minimum of the value range
---@param max integer Maximum of the value range
---@param segment_index integer Zero-based LED segment index
---@param segment_count integer Total number of LED segments
---@return integer intensity Segment brightness (0–255)
function segment_calculate(value, min, max, segment_index, segment_count) end

---Clamps *value* between *min* and *max*.
---@param value number
---@param min number
---@param max number
---@return number clamped
function limit(value, min, max) end

---Returns the sign of a number: -1, 0, or 1.
---@param value number
---@return integer sign
function sign(value) end

---Returns a pseudo-random integer in [0, 255].
---@return integer value
function random8() end

---------------------------------------------------------------------------
-- LED helpers
---------------------------------------------------------------------------

---Gets or sets the default red component of the LED.
---@param value? integer 0–255
---@return integer red Current value
function led_default_red(value) end

---Gets or sets the default green component of the LED.
---@param value? integer 0–255
---@return integer green Current value
function led_default_green(value) end

---Gets or sets the default blue component of the LED.
---@param value? integer 0–255
---@return integer blue Current value
function led_default_blue(value) end

---Gets or sets the LED phase value.
---@param value? integer
---@return integer phase Current value
function led_value(value) end

---Gets or sets the LED timeout.
---@param value? integer Timeout in ms
---@return integer timeout Current timeout
function led_timeout(value) end

---Gets or sets the LED color minimum intensity.
---@param value? integer 0–255
---@return integer min Current minimum
function led_color_min(value) end

---Gets or sets the LED color mid intensity.
---@param value? integer 0–255
---@return integer mid Current mid
function led_color_mid(value) end

---Gets or sets the LED color maximum intensity.
---@param value? integer 0–255
---@return integer max Current maximum
function led_color_max(value) end

---Sets or gets the LED color (composite helper).
---@param layer integer LED layer index
---@param colors table Array of {r, g, b, ?phase} tables
function led_color(layer, colors) end

---Gets or sets the LED animation rate.
---@param value? integer
---@return integer rate
function led_animation_rate(value) end

---Gets or sets the LED animation type / shape.
---@param value? integer
---@return integer shape
function led_animation_type(value) end

---Composite phase/frequency/shape setter.
---@param phase integer
---@param frequency integer
---@param shape integer
function led_animation_phase_rate_type(phase, frequency, shape) end

---Returns the hardware LED index for an element's n-th LED.
---@param element integer Element index
---@param n integer LED sub-index
---@return integer|nil hw_index Hardware LED index or nil if out of bounds
function led_address_get(element, n) end

---------------------------------------------------------------------------
-- HID — Keyboard / Mouse / Gamepad
---------------------------------------------------------------------------

---Sends an HID keyboard report.
---@param ... any Key parameters
function keyboard_send(...) end

---Sends an HID mouse-move report.
---@param axis integer Axis identifier
---@param position integer Movement delta
function mouse_move_send(axis, position) end

---Sends an HID mouse-button report.
---@param button integer Button index
---@param state integer 0 = release, 1 = press
function mouse_button_send(button, state) end

---Sends an HID gamepad axis report.
---@param axis integer Axis identifier
---@param position integer Position value
function gamepad_move_send(axis, position) end

---Sends an HID gamepad button report.
---@param button integer Button index
---@param state integer 0 = release, 1 = press
function gamepad_button_send(button, state) end

---------------------------------------------------------------------------
-- Module / System
---------------------------------------------------------------------------

---Returns the hardware configuration ID.
---@return integer hwcfg
function hardware_configuration() end

---@return integer major Firmware major version
function version_major() end

---@return integer minor Firmware minor version
function version_minor() end

---@return integer patch Firmware patch version
function version_patch() end

---@return integer x Module X position on the grid
function module_position_x() end

---@return integer y Module Y position on the grid
function module_position_y() end

---@return integer rotation Module rotation (0, 1, 2, 3)
function module_rotation() end

---Returns the number of elements on the current module.
---@return integer count
function element_count() end

---------------------------------------------------------------------------
-- Pages
---------------------------------------------------------------------------

---Switch to the next page.
function page_next() end

---Switch to the previous page.
function page_previous() end

---Returns the currently active page number.
---@return integer page
function page_current() end

---Loads a specific page.
---@param page integer Page number
function page_load(page) end

---------------------------------------------------------------------------
-- Timer
---------------------------------------------------------------------------

---Starts the element timer.
---@param element integer Element index
---@param period integer Period in ms
function timer_start(element, period) end

---Stops the element timer.
---@param element integer Element index
function timer_stop(element) end

---Returns the timer event source element.
---@return integer element
function timer_source() end

---------------------------------------------------------------------------
-- Events / Communication
---------------------------------------------------------------------------

---Triggers an event programmatically.
---@param element integer Element index
---@param event integer Event type
function event_trigger(element, event) end

---Sends a string via WebSocket.
---@param message string
function websocket_send(message) end

---Sends a package to the editor.
---@param message string
function package_send(message) end

---Executes Lua code on a remote module addressed by (x, y).
---Use x = nil and y = nil to trigger on all modules.
---@param x integer|nil Module X position (nil = all)
---@param y integer|nil Module Y position (nil = all)
---@param lua_code string Lua source to execute remotely
function immediate_send(x, y, lua_code) end

---------------------------------------------------------------------------
-- MIDI RX
---------------------------------------------------------------------------

---Gets or sets the MIDI-RX enabled flag.
---@param value? integer 0 or 1
---@return integer enabled
function midirx_enabled(value) end

---Gets or sets the MIDI-RX sync flag.
---@param value? integer
---@return integer sync
function midirx_sync(value) end

---------------------------------------------------------------------------
-- Element naming
---------------------------------------------------------------------------

---Sends the element name to the editor.
---@param element integer Element index
function element_name_send(element) end

---Sets an element's display name.
---@param element integer Element index
---@param name string New name
function element_name_set(element, name) end

---Gets an element's display name.
---@param element integer Element index
---@return string name
function element_name_get(element) end

---Alias helper for element_name_get / element_name_set.
---@param element integer Element index
---@param name? string Optional name to set
---@return string name
function element_name(element, name) end

---Gets a stored string value.
---@param key string
---@return string value
function string_get(key) end

---------------------------------------------------------------------------
-- Lookup / Decode
---------------------------------------------------------------------------

---Looks up a protocol value by key.
---@param key string
---@return any value
function lookup(key) end

---Decodes a serialized protocol value.
---@param data string
---@return any value
function decode(data) end

---------------------------------------------------------------------------
-- Filesystem
---------------------------------------------------------------------------

---Lists directory contents on the module flash.
---@return table entries
function readdir() end

---Reads a file from the module flash.
---@param path string File path
---@return string contents
function readfile(path) end

---------------------------------------------------------------------------
-- Calibration
---------------------------------------------------------------------------

---Deletes the calibration file and resets all calibrations to defaults.
function calibration_reset() end

---Returns raw potentiometer calibration values as an integer array.
---@return integer[] values
function potmeter_calibration_get() end

---Sets potentiometer calibration centres from an integer array.
---@param centres integer[]
function potmeter_center_set(centres) end

---Sets potentiometer detent bounds.
---@param values integer[] Detent bound array
---@param high boolean true = high bounds, false = low bounds
function potmeter_detent_set(values, high) end

---Returns raw min/max range values as an array of {min, max} arrays.
---@return integer[][] ranges
function range_calibration_get() end

---Sets min/max range values from an array of {min, max} arrays.
---@param ranges integer[][]
function range_calibration_set(ranges) end

---------------------------------------------------------------------------
-- GUI Draw (global screen_index variants)
---------------------------------------------------------------------------

---Swaps the background buffer to the screen.
---@param screen_index integer
function gui_draw_swap(screen_index) end

---Draws a single pixel.
---@param screen_index integer
---@param x integer
---@param y integer
---@param color integer[] {r, g, b}
function gui_draw_pixel(screen_index, x, y, color) end

---Draws a line.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function gui_draw_line(screen_index, x1, y1, x2, y2, color) end

---Draws a rectangle outline.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function gui_draw_rectangle(screen_index, x1, y1, x2, y2, color) end

---Draws a filled rectangle.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function gui_draw_rectangle_filled(screen_index, x1, y1, x2, y2, color) end

---Draws a rounded rectangle outline.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param radius integer Corner radius in pixels
---@param color integer[] {r, g, b}
function gui_draw_rectangle_rounded(screen_index, x1, y1, x2, y2, radius, color) end

---Draws a filled rounded rectangle.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param radius integer Corner radius in pixels
---@param color integer[] {r, g, b}
function gui_draw_rectangle_rounded_filled(screen_index, x1, y1, x2, y2, radius, color) end

---Draws a polygon outline.
---@param screen_index integer
---@param xs integer[] X coordinates
---@param ys integer[] Y coordinates
---@param color integer[] {r, g, b}
function gui_draw_polygon(screen_index, xs, ys, color) end

---Draws a filled polygon.
---@param screen_index integer
---@param xs integer[] X coordinates
---@param ys integer[] Y coordinates
---@param color integer[] {r, g, b}
function gui_draw_polygon_filled(screen_index, xs, ys, color) end

---Draws text at (x, y).
---@param screen_index integer
---@param text string
---@param x integer
---@param y integer
---@param size integer Font size
---@param color integer[] {r, g, b}
function gui_draw_text(screen_index, text, x, y, size, color) end

---Draws text using the fast renderer.
---@param screen_index integer
---@param text string
---@param x integer
---@param y integer
---@param size integer Font size
---@param color integer[] {r, g, b}
function gui_draw_fasttext(screen_index, text, x, y, size, color) end

---Fills an area without alpha blending.
---@param screen_index integer
---@param x1 integer
---@param y1 integer
---@param x2 integer
---@param y2 integer
---@param color integer[] {r, g, b}
function gui_draw_area_filled(screen_index, x1, y1, x2, y2, color) end

---Draws the n-th demo iteration.
---@param screen_index integer
---@param n integer Iteration number
function gui_draw_demo(screen_index, n) end

---Returns render time between last two swaps, in microseconds.
---@param screen_index integer
---@return integer us
function gui_get_render_time(screen_index) end

---Sets the LCD backlight brightness.
---@param strength integer 0–255
function lcd_set_backlight(strength) end

---------------------------------------------------------------------------
-- Auto-configuration helpers (user-overridable)
---------------------------------------------------------------------------

---Calculates the default MIDI channel from grid position.
---@param self any Element reference
---@return integer channel 0–15
function midi_auto_ch(self) end

---Calculates the default MIDI command type.
---Returns 144 (Note On) for button events, 176 (CC) for others.
---@param self any Element reference
---@return integer command
function midi_auto_cmd(self) end

---Calculates the default MIDI parameter 1 (note/CC number).
---@param self any Element reference
---@return integer param1 0–127
function midi_auto_p1(self) end

---Calculates the default MIDI parameter 2 (velocity/value).
---@param self any Element reference
---@return integer param2
function midi_auto_p2(self) end

---Calculates LED layer based on current event type.
---@param self any Element reference
---@return integer|nil layer 1 for button/pot, 2 for encoder, nil otherwise
function color_auto_layer(self) end

---Calculates LED intensity value based on element type and state.
---@param self any Element reference
---@param segment_index integer Segment index for endless encoders
---@return integer value 0–255
function color_auto_value(self, segment_index) end

---Calculates intensity response curve from color array.
---Processes -1 values as current LED colors.
---@param color_array table Array of color values
---@return table min_colors
---@return table mid_colors
---@return table max_colors
function color_curve(color_array) end
